spring.application.name=notification-service

# Run on port 8081 (main app uses 8080)
server.port=8081

# Email Configuration (Gmail SMTP) - imports secrets
spring.config.import=optional:application-secret.properties